### ISSUE TITLE
More Information regarding the exploitation

### ISSUE THREAD

**Issue by willzavado** [oskarsve/ms-teams-rce#12]
Hello @oskarsve ,

Great find, and thanks for sharing this to the public. I found it really informative. I totally think you should share more of your electron bugs (if you have discovered more). 

I have a lot of questions to you. I require more information to better understand your exploit. Would be really helpful to have insights onto those.

While looking at the exploit, you mentioned that `remote-require` is disabled & filtered, `nodeIntegration` is false and creating `webview` with a custom preload option is disabled. 

Here, I assume that following IPC channel is responsible for whitelisting certain url which could be opened: `allowWindowOpenUrl` . I'm purely guessing as I haven't reversed the MS Teams yet, but correct me if I am wrong.   -- Question 1

```html
stage2 = `data:text/html,<webview src='about:blank' preload='file:///${f}'></webview>`
...
window.open(stage2)
```

To understand this part more better, I was testing just this locally, and unless I didn't setup `disablewebsecurity: false` , the `window.open` didn't actually worked. It threw an error otherwise. But, if I had `disablewebsecurity: true` , then in a scenario of DOM XSS, I could utilize it to get `preload` work. In your writeup, I didn't see that Microsoft has disabled `disablewebsecurity` anywhere, so I'm curious how was that allowed. (Note that, I tested on Electron 9.3.1).  -- Question 2

Another question, Is regarding how the `window.open(stage2)` is triggering internally. Is the `window.open` action equivalent to defining a fresh new `BrowserWindow` where different set of rules/attributes could be applied?  -- Question 3

Also, do you know how could you get access to `require-remote` assuming it's enabled but `nodeIntegration` is disabled. From what I understand, NodeIntegration disabled, takes the ability to require through the DOM via XSS. Hence, I don't see a way to abuse that.  -- Question 4

### Out of Scope Question

Sorry that I am asking you this here, as I was unable to find your twitter for direct communication. I was looking at your report here: https://hackerone.com/reports/783877 . After Slack patched it, You mentioned that

```
It would be of course completely different. Working in 4.4.0 (bypassing contextIsolation) and older 4.x versions.
```

Do you have any POC of how did you achieved that? Because it seems to be a core electron issue if you could bypass `contextIsolation: true`, no?   -- Question 5

Would like to chat with you directly if you have a twitter else Github all the way ;)

**Comment by oskarsve** [comment]
1. Yes, it only whitelists it for a filtered `window.open`, so you can open any URL (including protocol) in a new window - new windows are almost always 'interesting' in Electron world
2. I don't remember, I don't think `disablewebsecurity` was defined - i.e. it was default/true/non-existant for that Electron version (4.x.x)
3. different rules in the sense that `webview` in this specific way (I think because the electron version was 4.x.x) could be created with a `preload` attribute. it was not possible directly from the main process
4. `remote` was disabled, however if you can use `preload` those rules don't apply. `preload` is by definition node enabled environment

OOS Slack q:

It was not a global Electron issue. If Slack permits it, the report will go public
