### ISSUE TITLE
Host: null bypass?

### ISSUE THREAD

**Issue by JLLeitschuh** [oskarsve/ms-teams-rce#9]
Any chance you tried the `Host: null` bypass to allow this exploit request to be sent cross-origin?

`<iframe sandbox="allow-scripts allow-top-navigation allow-forms" src='data:text/html,<script>*cors stuff here*</script>’></iframe>`

https://portswigger.net/research/exploiting-cors-misconfigurations-for-bitcoins-and-bounties

**Comment by willzavado** [comment]
Interesting, can you elaborate this approach and exactly where do you think this could have been used in his existing exploit payload? 

From what I think, I don't think you could trigger this exploit through `iframe`, because `window.open` allows the ability to create a window which should create the window with `webview` + `preload` tag. Isn't it?

I have filed #12 to ask him specificity of the `window.open` requirement however.
